on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: hello World Action
        run: |
          curl -H "Autorization: Bearer ${{secrets.API_KEY }}" https://www.google.co.in
